spring:
  datasource:
    url: jdbc:mysql://localhost:3306/college_prod?&useTimezone=true&serverTimezone=UTC
    username: college_prod_user
    password: rusinek
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false
